//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorldLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class HelloWorldSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HelloWorldSettings defaultInstance = ((HelloWorldSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HelloWorldSettings())));
        
        public static HelloWorldSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Console")]
        public string DefaultOutputTarget {
            get {
                return ((string)(this["DefaultOutputTarget"]));
            }
            set {
                this["DefaultOutputTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ConsoleApp")]
        public string TargetPlatform {
            get {
                return ((string)(this["TargetPlatform"]));
            }
            set {
                this["TargetPlatform"] = value;
            }
        }
    }
}
